// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrC5ob_l8WgNWc0Yrn6N22LwgXLBf7FsQ',
    appId: '1:646210267861:web:bd39f3d711f7e124bad05c',
    messagingSenderId: '646210267861',
    projectId: 'mygateapp-a2a4b',
    authDomain: 'mygateapp-a2a4b.firebaseapp.com',
    storageBucket: 'mygateapp-a2a4b.appspot.com',
    measurementId: 'G-V01B6FM10P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9ZyfYyhRCNgfwFaAwtQ7rYCVWV4NskQ',
    appId: '1:646210267861:android:1c1e8be25ad2dc67bad05c',
    messagingSenderId: '646210267861',
    projectId: 'mygateapp-a2a4b',
    storageBucket: 'mygateapp-a2a4b.appspot.com',
  );
}
